### ISSUE TITLE
Worker problem multi-thread

### ISSUE THREAD

**Issue by mhdg** [ralph-group/pymeasure#142]
Hi all, I'm having problems to run a program that works fine in an old computer (Win7, Anaconda Python 3.6.3), but doesn't work in a new one (Win10, Anaconda Python 3.6.5, although I tried downgrading python too).

Is it a problem with how the plotter is coded? It seems that the error is coming from the multi-thread in worker.

Thanks in advance for the help!

>(base) C:\Users\PhysFNA2\surfdrive\Measurement-Programs>ipython RvsVg_2KEITHLEYs.py
C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\sugar\socket.py", line 426, in send_multipart
    memoryview(msg)
TypeError: memoryview: a bytes-like object is required, not 'int'

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymeasure\experiment\workers.py", line 161, in run
    self.update_status(Procedure.RUNNING)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymeasure\experiment\workers.py", line 115, in update_status
    self.emit('status', status)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymeasure\experiment\workers.py", line 95, in emit
    self.publisher.send_serialized((topic, record), serialize=cloudpickle.dumps)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\sugar\socket.py", line 511, in send_serialized
    return self.send_multipart(frames, flags=flags, copy=copy, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\sugar\socket.py", line 433, in send_multipart
    i, rmsg,
TypeError: Frame 0 (128) does not support the buffer interface.

**Comment by mhdg** [comment]
I've found a workaround with a fresh install of python 3.5. Everything seems to work well except of opening old measurements. Could the problem be in one of the new versions of the standard python packages?

**Comment by cjermain** [comment]
@mhdg, from the error messages, both of the errors appear to be external to PyMeasure. It seems as though you might be having a problem with zmq. What version are you using?

**Comment by cjermain** [comment]
This seems to be resolved. If not please re-open the issue.
