### ISSUE TITLE
Log error in sample/GUI !  

### ISSUE THREAD

**Issue by hongcaihao** [ralph-group/pymeasure#223]
I ran the sample/GUI/py in spyder3.6. The error show in log !
09/08/2019 02:46:05 PM : ManagedWindow connected to logging (INFO)
09/08/2019 02:46:07 PM : Worker thread started (INFO)
09/08/2019 02:46:07 PM : couldn't connect to ZMQ context (ERROR)
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\pymeasure\experiment\workers.py", line 154, in run
    self.publisher.bind('tcp://*:%d' % self.port)
  File "zmq/backend/cython/socket.pyx", line 555, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address in use
09/08/2019 02:46:07 PM : Worker started running an instance of 'TestProcedure' (INFO)

How to reslove the ZMQ.error?

**Comment by hongcaihao** [comment]
I have modified as Kassikakk commented on 20 Jun in  #168 issue!
This problem had resolved!
