### ISSUE TITLE
Startup method does not initialize instrument for IV measurements

### ISSUE THREAD

**Issue by PYmeas** [ralph-group/pymeasure#315]
Hello,

I ve been struggling for a while with an IV `procedure `using a Keithley 2400 and display with `Managedwindow`. While i dont have any issue when i use the fake data as in the tutorial when i implement the Keithley in the `startup `method i get an Attribute error on the instrument: AttributeError: 'IVProcedure' object has no attribute 'sourcemeter'. If i run the IV in a standalone code without any procedure i do get a normal acquisition and my .csv file records the proper measurements so i am convinced i dont have communication nor command issues. I tried to shortcut the `startup `method and initialize the instrument in a separate  `def __init__(self, **kwargs):`
method. I get a communication but there is no data acquisition and the instrument displays a error ID code 803 and the log in the a bunch of errors as below:

log for `managedwindow `when running the procedure, i put the code right after:

08/31/2020 10:30:18 PM : ManagedWindow connected to logging (INFO)
08/31/2020 10:30:18 PM : Connecting and configuring the instrument (INFO)
08/31/2020 10:30:19 PM : Initializing Keithley 2400 SourceMeter. (INFO)
08/31/2020 10:30:19 PM : Keithley 2400 SourceMeter is sourcing current. (INFO)
08/31/2020 10:30:22 PM : Connecting and configuring the instrument (INFO)
08/31/2020 10:30:22 PM : Initializing Keithley 2400 SourceMeter. (INFO)
08/31/2020 10:30:23 PM : Keithley 2400 SourceMeter is sourcing current. (INFO)
08/31/2020 10:30:23 PM : Constructing the Results with a data file: .\test\test2\data_08312020_1.csv (INFO)
08/31/2020 10:30:24 PM : Connecting and configuring the instrument (INFO)
08/31/2020 10:30:24 PM : Initializing Keithley 2400 SourceMeter. (INFO)
08/31/2020 10:30:25 PM : Keithley 2400 SourceMeter is sourcing current. (INFO)
08/31/2020 10:30:25 PM : Constructing the Results with a data file: .\test\test2\data_08312020_2.csv (INFO)
08/31/2020 10:30:25 PM : Worker thread started (INFO)
08/31/2020 10:30:25 PM : Worker started running an instance of 'IVProcedure' (INFO)
08/31/2020 10:30:25 PM : Setting the current to -0.01 A (INFO)
08/31/2020 10:30:25 PM : Keithley 2400 SourceMeter is measuring voltage. (INFO)
08/31/2020 10:30:28 PM : Worker caught an error on <IVProcedure(status=Running,parameters_are_set=True)> (ERROR)
Traceback (most recent call last):
  File "C:\Users\PycharmProjects\automated measurements\venv\lib\site-packages\pymeasure\experiment\workers.py", line 166, in run
    self.procedure.execute()
  File "D:/coding/IV Procedure.py", line 203, in execute
    'Voltage (V)': self.sourcemeter.voltage,
  File "C:\Users\PycharmProjects\automated measurements\venv\lib\site-packages\pymeasure\instruments\instrument.py", line 216, in fget
    vals = self.values(command_process(get_command), **kwargs)
  File "C:\Users\PycharmProjects\automated measurements\venv\lib\site-packages\pymeasure\instruments\instrument.py", line 111, in values
    return self.adapter.values(command, **kwargs)
  File "C:\PycharmProjects\automated measurements\venv\lib\site-packages\pymeasure\adapters\adapter.py", line 71, in values
    results = str(self.ask(command)).strip()
  File "C:\Users\PycharmProjects\automated measurements\venv\lib\site-packages\pymeasure\adapters\visa.py", line 112, in ask
    return self.connection.query(command)
  File "C:\Users\PycharmProjects\automated measurements\venv\lib\site-packages\pyvisa\resources\messagebased.py", line 613, in query
    return self.read()
  File "C:\Users\PycharmProjects\automated measurements\venv\lib\site-packages\pyvisa\resources\messagebased.py", line 427, in read
    message = self._read_raw().decode(enco)
  File "C:\Users\PycharmProjects\automated measurements\venv\lib\site-packages\pyvisa\resources\messagebased.py", line 400, in _read_raw
    chunk, status = self.visalib.read(self.session, size)
  File "C:\Users\PycharmProjects\automated measurements\venv\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1584, in read
    ret = library.viRead(session, buffer, count, byref(return_count))
  File "C:\PycharmProjects\automated measurements\venv\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 193, in _return_handler
    raise errors.VisaIOError(ret_value)
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.
08/31/2020 10:30:28 PM : Shutting down Keithley 2400 SourceMeter. (INFO)
08/31/2020 10:30:29 PM : Finished measuring (INFO)
08/31/2020 10:30:29 PM : Monitor caught stop command (INFO)

code:

``` ruby
import logging
log = logging.getLogger(__name__)
log.addHandler(logging.NullHandler())
import sys
from datetime import datetime as dt, timedelta
from time import sleep
import pandas as pd
import numpy as np
from pymeasure.instruments.keithley import Keithley2400
from pymeasure.log import console_log
from pymeasure.display.Qt import QtGui
from pymeasure.display.windows import ManagedWindow
from pymeasure.experiment import Procedure, Results, Worker
from pymeasure.experiment import IntegerParameter, FloatParameter, Parameter

class IVProcedure(Procedure):
    # averages = IntegerParameter('Averages', default=50)
    min_current = FloatParameter('Minimum Current', units='A', default=-0.01)
    max_current = FloatParameter('Maximum Current', units='A', default=0.01)
    data_points = IntegerParameter('Data points', default=50)
    mode = IntegerParameter('2 or 4 probes measurement', default=2)

    DATA_COLUMNS = ['Time', 'Current (A)', 'Voltage (V)']

    # if use a def__ can have the instrument initialized but no measurements
    def __init__(self):
        super().__init__()
        log.info("Connecting and configuring the instrument")
        self.sourcemeter = Keithley2400("ASRL6::INSTR")  # using RS 232 COM6
        self.sourcemeter.enable_source()
        sleep(0.1)
        self.sourcemeter.reset()
        sleep(0.1)
        self.sourcemeter.use_front_terminals()
        sleep(0.1)
        self.sourcemeter.wires = self.mode  # type 4 for 4 terminals measurement
        sleep(0.1)
        self.sourcemeter.apply_current()
        sleep(0.1)
        self.sourcemeter.source_current = self.min_current
        sleep(0.1)
        # sourcemeter.measure_resistance()

   # this method doesnt initialize the instrument and i get an attribute error
    # def startup(self):
    #     log.info("Connecting and configuring the instrument")
    #     self.sourcemeter = Keithley2400("ASRL6::INSTR")  # using RS 232 COM6
    #     self.sourcemeter.enable_source()
    #     sleep(0.1)
    #     self.sourcemeter.reset()
    #     sleep(0.1)
    #     self.sourcemeter.use_front_terminals()
    #     sleep(0.1)
    #     self.sourcemeter.wires = self.mode  # type 4 for 4 terminals measurement
    #     sleep(0.1)
    #     self.sourcemeter.apply_current()
    #     sleep(0.1)
    #     self.sourcemeter.source_current = self.min_current
    #     sleep(0.1)
    #     # sourcemeter.measure_resistance()

    def execute(self):
        currents = np.linspace(
            self.min_current,
            self.max_current,
            num=self.data_points
        )
        for current in currents:
            log.info("Setting the current to %g A" % current)
            self.timecode = dt.now()
            self.sourcemeter.source_current = current  # Sets the source current to min current mA
            sleep(0.1)
            self.sourcemeter.measure_voltage()
            sleep(0.1)
            data = {
                'Time': self.timecode,
                'Current (A)': current,
                'Voltage (V)': self.sourcemeter.voltage,
            }
            self.emit('results', data)
            log.debug("Emitting results: %s" % data)
            sleep(0.1)
            if self.should_stop():
                log.info("User aborted the procedure")
                break

    def shutdown(self):
        self.sourcemeter.shutdown()
        log.info("Finished measuring")

class MainWindow(ManagedWindow):

    def __init__(self):
        super(MainWindow, self).__init__(
            procedure_class=IVProcedure,
            inputs=['min_current', 'max_current', 'data_points', 'mode'],
            displays=['min_current', 'max_current', 'data_points', 'mode'],
            x_axis='Voltage (V)',
            y_axis='Current (A)',
            # sequencer=True,  # Added line
            # sequencer_inputs=['min_current', 'max_current', 'data_points', 'mode'],  # Added line
            # sequence_file="gui_sequencer_example_sequence.txt",  # Added line, optional if load a sequence file
        )
        self.setWindowTitle('IV procedure')
        self.count = 0

    def queue(self, *, procedure=None):
        self.count = self.count + 1
        if procedure is None:
            procedure = self.make_procedure()
        filename = '.\\test\\test2\\' + 'data_' + str(dt.now().strftime("%m%d%Y"))+'_' + str(self.count) + '.csv'
        log.info("Constructing the Results with a data file: %s" % filename)
        results = Results(procedure, filename)
        experiment = self.new_experiment(results)
        self.manager.queue(experiment)

if __name__ == "__main__":
    app = QtGui.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())
```

 i dont see where is the conflict if anyone in the community could help. Thanks

**Comment by PYmeas** [comment]
I managed to get measurements but the `startup `method is still not functional by putting the initialization commands in a `def__ini__ `method it works fine. I dont get it. the commands are the same and my understanding was that the `startup `method is meant to initilalize the instruments.

``` ruby
  # if use a def__ini __ the instrument initializes and get measurements
    def __init__(self):
        super().__init__()
        log.info("Connecting and configuring the instrument")
        self.sourcemeter = Keithley2400("ASRL6::INSTR")  # using RS 232 COM6
        self.sourcemeter.reset()
        self.sourcemeter.use_front_terminals()
        self.sourcemeter.wires = self.mode  # type 4 for 4 terminals measurement
        self.sourcemeter.apply_current()
        # self.sourcemeter.source_current = self.min_current
        # sourcemeter.measure_resistance()
        self.sourcemeter.enable_source()

   # i use the startup method the instrument doesnt initialize and i get an attribute error
    def startup(self):
        log.info("Connecting and configuring the instrument")
        self.sourcemeter = Keithley2400("ASRL6::INSTR")  # using RS 232 COM6
        self.sourcemeter.reset()
        self.sourcemeter.use_front_terminals()
        self.sourcemeter.wires = self.mode  # type 4 for 4 terminals measurement
        self.sourcemeter.apply_current()
        # self.sourcemeter.source_current = self.min_current
        # sourcemeter.measure_resistance()
        self.sourcemeter.enable_source()
```

**Comment by PYmeas** [comment]
parenthesis of the startup method were missing in the Worker.py file. issue solved.
